### ISSUE TITLE
Roadmap to have PhenoScanner V3? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [phenoscanner/phenoscanner#4]
Dear Team, 

PhenoScanner is really an awesome tool. I am wondering is there any roadmap to have PhenoScanner V3 to support more knowledge, annotation, inference and prediction?

Thanks. 

Shicheng

**Comment by phenoscanner** [comment]
Hi Shicheng,

Thanks very much for your kind words. Unfortunately, a new version of PhenoScanner will depend on funding.

Best wishes,

PhenoScanner Team
